version: "3.9"

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb_restapi
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  restapi:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    restart: always
  