version: "3.9"

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb_restapi
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  restapi:
    build: .
    volumes:
      - ./application:/app/application
    environment:
      - FLASK_ENV=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb_restapi
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
    ports:
      - 5000:5000
    restart: always
  