name: RestAPI Flask

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pytest
        pip install --upgrade "flake8==7.1.2" "mccabe>=0.7.0,<0.8.0" "pycodestyle>=2.12.0,<2.13.0" "pyflakes>=3.2.0,<3.3.0"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Flake8 and PyTest
      run: |
        make flake
